### ISSUE TITLE
[文档修复]一月暂定修复

### ISSUE THREAD

**Issue by Fan-Lin** [DaoCloud/DaoCloud-docs#3398]
**应用工作台amamba**

https://docs.daocloud.io/amamba/pluggable-components/

- [x] 部署应用工作台可插拔组件 #3411  
- [x] 基于 Jar 包部署 Java 应用 #3414 
- [x] 基于 Helm 模板部署 Helm 应用 #3421 

**全局管理ghippo**

https://docs.daocloud.io/ghippo/user-guide/workspace/folders/

- [x] 创建删除文件夹 #3425 
- [ ] 密码重置（**缺少权限，或无法更新**）
https://docs.daocloud.io/ghippo/user-guide/password/#_3
- [x] 安全设置 #3431
https://docs.daocloud.io/ghippo/user-guide/personal-center/security-setting/

**存储hwameistor**

https://docs.daocloud.io/storage/hwameistor/install/drbdinstall/

- [x] 安装DRDB #3445 
- [x] Install with Operator #3445 
- [ ] Install with UI（**hwameistor插件没找到，中文导航栏要更改**）
https://docs.daocloud.io/storage/hwameistor/install/deploy-ui/#_3

**可观测性insight**

https://docs.daocloud.io/insight/user-guide/dashboard/dashboard.html#_2

- [x] 仪表盘 #3448 
- [ ] #3626
- [ ] 导入自定义仪表盘（**grafanadashboards.integreatly.org 文件缺失**）

**多云kairship**

https://docs.daocloud.io/kairship/crds/crd/
- [x] 多云自定义资源 #3453 
- [x] DCE4.0 - DCE5.0 #3465 
https://docs.daocloud.io/kairship/best-practice/one-click-conversion/
- [x] 跨集群弹性伸缩 #3468 

**镜像仓库kangaroo**

**云边协同kant**

https://docs.daocloud.io/kant/user-guide/device/create-device/

- [x] 创建终端设备 #3470 
- [x] 管理终端设备 #3470 
- [x] 创建工作负载 #3472 
https://docs.daocloud.io/kant/user-guide/edge-app/create-app/

**容器管理kapanda**

https://docs.daocloud.io/kpanda/user-guide/clusters/upgrade-cluster/

- [ ] 集群升级（**等待测试集群环境**）
- [x] 安装 velero 插件 #3581 
https://docs.daocloud.io/kpanda/user-guide/backup/install-velero/
- [x] 应用备份 #3585 

**安装器kubean**

**中间件mcamel**

https://docs.daocloud.io/middleware/common/

- [x] 首次进入 #3438 
- [x] 配置管理 #3588 
- [x] 工作负载反亲和性 #3588 

**服务网格mspider**

https://docs.daocloud.io/mspider/user-guide/security/peer/

- [x] 网关规则 #3393 
- [x] 对等身份认证 #3403
- [x] 请求身份认证 #3406

**微服务引擎skoala**

https://docs.daocloud.io/skoala/standard/sentinel/

- [x] 服务接入 Sentinel 规范 #3591 

**网络spidernet**

https://docs.daocloud.io/network/modules/ingress-nginx/install/

- [x] 安装 ingress-nginx #3434 

**虚拟机virtnest**

https://docs.daocloud.io/virtnest/quick-start/snapshot.html

- [x] 快照管理 #3644

**Comment by windsonsea** [comment]
most are resolved, this will be closed.
