### ISSUE TITLE
文档站 ChatBot Roadmap, 含候选方案,可点赞投票

### ISSUE THREAD

**Issue by windsonsea** [DaoCloud/DaoCloud-docs#5778]
## 排期 Schedule

目前大家倾向于使用自己的产品 [d.run/dak](https://console.d.run/dak/ws/302/ai-assistant)，争取 11 月上线 ChatBot。

参见 PR #5969  和[预览](https://deploy-preview-5969--daocloud-docs.netlify.app/)。

- [ ] 11.01-11.10：DCE 所有页面的数据清洗，制作语料库  @Zhuzhenghao @samzong @windsonsea 
- [ ] 11.10-11.15：创建应用智能体、前端 SDK @Zhuzhenghao 
- [ ] 提 PR 展示预览页面 @windsonsea 
- [ ] 11.15-11.22 测试 @liyuerich 
- [ ] 上线 @windsonsea 
- [ ] 上线后发现样式冲突 bug： https://github.com/d-run/drun-docs/issues/152 ，考虑暂时先下线，通过 预览来体验吧

## Roadmap

- [ ] 文档站的数据格式化：
  - [ ] 去除所有图片
  - [ ] 中英文独立处理
  - [ ] 数据格式要符合要求（利用 OpenAI 做数据提取）
- [ ] 选一个模型
- [ ] 模型训练/微调，加入所有文档数据
- [ ] 模型评分，准备一个测试数据集
- [ ] 将模型部署为推理服务
- [ ] 挂接到文档站
  - [ ] ChatBot 前端页面
  - [ ] 后端加一个聊天泡泡
 
## 后续维护

- [ ] 新增内容持续更新，与网站内容保持同步
- [ ] 回复的问题跳转到文档页，或添加链接
- [ ] 提高回答的准确性，持续微调
- [ ] 收集用户数据，整理常见问题，完善对应页面

**Comment by windsonsea** [comment]
## 方案一：扣子

https://www.coze.cn/

- 全 UI 无代码操作
- 给网址就会自己拆分数据
- 可以根据网站内容按 1-7 天自动更新数据

![image](https://github.com/user-attachments/assets/70d560c9-0c69-4b49-93c1-17b255197a2d)

**Comment by windsonsea** [comment]
## 方案二：chatwith

https://chatwith.tools/

- Google 排名靠前的 website chatbot
- 对海外用户友好，全英文操作

参见 PR #5776  和[预览](https://deploy-preview-5776--daocloud-docs.netlify.app/)

![image](https://github.com/user-attachments/assets/eb26ccf7-3b14-46c9-8482-986737aba8fd)

**Comment by windsonsea** [comment]
## 方案三：d.run

https://console.d.run/dak/

- 我们自己的产品，打磨使用可促进完善
- 需要手动拆分数据（2000+ markdown 文件）
- 智能体后期怎么与网站同步？
- 需要前端 Web 参与，或增加一个 iframe 插件

**Comment by windsonsea** [comment]
## 方案三的补充：借助一些工具 aitools

整理文件时，手工对文件进行打标签是无法避免的，打好标签后，可以直接运行脚本将word文档或者xlsx文档直接转出成标准的zip格式导入智能体应用。

aitools 的安装方式之一：
```
# 实际使用镜像方式，注意 linux 适用 4.1 版本，如果是 mac 请使用 3.1 版本
docker run -p 8888:8888 -e JUPYTER_TOKEN=[请替换成你需要的token] [registry.cn-shanghai.aliyuncs.com/clipper/aitools:3.1](http://registry.cn-shanghai.aliyuncs.com/clipper/aitools:3.1)
```
![image](https://github.com/user-attachments/assets/cba05cba-2402-48e2-bd39-df73a01a238f)

说明：
- 需要有一定后端基础，用镜像等方式部署工具
- 借助 python 等脚本批量处理 markdown、docx
- 然后喂给 d.run 知识库
- 同样问题：怎么能跟网站保持同步？每次都手动吗？

**Comment by samzong** [comment]
1. 方案三考虑也迁入到 dce 内，做个效果，先简单手工做几个文档
2. 可以考虑从整体使用过程，和咱们需要的功能做个横向对比，like 参数表

**Comment by Zhuzhenghao** [comment]
> ## 方案三：d.run/dak
> https://console.d.run/dak/
> 
> * 自己的产品自主可控，打磨使用可促进完善
> * 需要手动拆分数据（2000+ markdown 文件）
> * 智能体后期怎么与网站同步？
> * 需要前端 Web 参与，或增加一个 iframe 插件
> 
> 参见[预览](https://console.d.run/ai-chat-app/ai-chat?mode=mobile&ws=302&token=MGU4Zjg1OTItYzRhZi00ZjI1LTlhODItYTQxYWVhMjJhMWZi)
> 
> ![image](https://private-user-images.githubusercontent.com/79828097/381352113-5b6e42e1-805d-4f63-8fc6-7b142d81cc67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTcwMzIsIm5iZiI6MTczMDI1NjczMiwicGF0aCI6Ii83OTgyODA5Ny8zODEzNTIxMTMtNWI2ZTQyZTEtODA1ZC00ZjYzLThmYzYtN2IxNDJkODFjYzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZWUwZTA1NWYwNTkwODE4ZmM1OTVhMDY5MDc5MDdiNzNjNzFkMjQxMzZmNmI3MzJjMWQ3N2U2YWNjMzdiYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dBMCUiieD80bzQWVhHvszJYacEQNRR6lzSWA3cB7OgU)

1. 数据可以使用粗略的分片，一个文件就是一个分片，使用上下文 128K 的模型，先出一个MVP
2. 文档站更新后，需要更新语料库

PS：可以打磨公司产品，积累场景解决方案
![image](https://github.com/user-attachments/assets/ded0c1a8-f3c9-44fe-84a0-d87b00e179f6)

**Comment by Zhuzhenghao** [comment]
> ## 方案三的补充：借助一些工具 aitools
> 整理文件时，手工对文件进行打标签是无法避免的，打好标签后，可以直接运行脚本将word文档或者xlsx文档直接转出成标准的zip格式导入智能体应用。
> 
> aitools 的安装方式之一：
> 
> ```
> # 实际使用镜像方式，注意 linux 适用 4.1 版本，如果是 mac 请使用 3.1 版本
> docker run -p 8888:8888 -e JUPYTER_TOKEN=[请替换成你需要的token] [registry.cn-shanghai.aliyuncs.com/clipper/aitools:3.1](http://registry.cn-shanghai.aliyuncs.com/clipper/aitools:3.1)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/79828097/381353089-cba05cba-2402-48e2-bd39-df73a01a238f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTcwMTIsIm5iZiI6MTczMDI1NjcxMiwicGF0aCI6Ii83OTgyODA5Ny8zODEzNTMwODktY2JhMDVjYmEtMjQwMi00OGUyLWJkMzktZGY3M2EwMWEyMzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMWI5ZTgyNDRhOTNhNDFlZWU5YTFkNGQyNWI5NmU3MTQ1OTVmYzMxMTllM2UwZjFhM2E5NmI2YmZkNmFkNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KklbRKjsykvJRRLwROw1iyW2Xv2J6JKXgXQBcAwn-pc)
> 
> 说明：
> 
> * 需要有一定后端基础，用镜像等方式部署工具
> * 借助 python 等脚本批量处理 markdown、docx、xlsx
> * 然后喂给 d.run 知识库
> * 同样问题：怎么能跟网站保持同步？每次都手动吗？

线上已经部署好这个工具，https://console.d.run/ai-tools/lab

**Comment by Zhuzhenghao** [comment]
> * 去除所有图片

为啥要去除图片？

**Comment by samzong** [comment]
> > * 去除所有图片
> 
> 为啥要去除图片？

这个是我想的，问答最后还是引流到对应的文档即可，不需要图片。

**Comment by windsonsea** [comment]
ChatBot 已上线，请参阅网站： https://docs.daocloud.io/

维护 ChatBot 的说明，请参阅： https://docs.daocloud.io/native/git/chatbot/
